REGISTRY=docker.io/oubeyd
REGISTRY_CRED_ID=dockerhub-token
GIT_CRED_ID=github-token

BUILD_AGENT_LABEL=built-in
DEV_DEPLOY_AGENT_LABEL=wso2-dev-server
DEPLOY_AGENT_LABEL=wso2-dev-server
DEPLOY_DOCKER_NETWORK=wso2-mi-net

SMOKE_BASE_URL=http://localhost:8290

DEV_CONTAINER_NAME=wso2-mi-dev
DEV_CONTAINER_PORTS=-p 8290:8290 -p 8253:8253 -p 9164:9164
WSO2_BASE_IMAGE=wso2/wso2mi:4.6.0
WSO2_SERVER_HOME=/home/wso2carbon/wso2mi-4.6.0

TRIVY_FS_CACHE_DIR=/var/jenkins_home/trivy-cache
TRIVY_IMAGE_CACHE_DIR=C:\trivy-cache
TRIVY_SKIP_DB_UPDATE=true
TRIVY_TIMEOUT=5m

SONAR_ENABLED=true
SONAR_HOST_URL=http://host.docker.internal:9000
SONAR_SERVER_NAME=SonarQube
SONAR_SCANNER_TOOL=SonarScanner
SONAR_TOKEN_CRED_ID=sonarqube-token
SONAR_QUALITY_GATE=report

ICP_URL=https://integration-control-plane:9445
ICP_ENVIRONMENT=dev
ICP_PROJECT=wso2-mi-project
ICP_SECRET_CRED_ID_PREFIX=icp-runtime-secret
ICP_CONTAINER_NAME=integration-control-plane
ICP_KEYSTORE_PATH=/home/wso2carbon/wso2-integration-control-plane-2.0.0/conf/security/wso2carbon.jks
ICP_KEYSTORE_ALIAS=wso2carbon
ICP_KEYSTORE_PASSWORD=wso2carbon
MI_TRUSTSTORE_PATH=/home/wso2carbon/wso2mi-4.6.0/repository/resources/security/client-truststore.jks
MI_TRUSTSTORE_PASSWORD=wso2carbon

FAILURE_EMAIL_RECIPIENTS=oubeyd887@gmail.com
